### ISSUE TITLE
The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by CoooWeee** [tappollo/booster#28]
yarn install is giving me:
```
error @mercy/functions@0.0.1: The engine "node" is incompatible with this module. Expected version "10". Got "13.5.0"
error Found incompatible module.
```

I updated functions/package.json:
```
...
  "engines": {
    "node": "13"
  }
...
```

**Comment by zhigang1992** [comment]
> Because firebase cloud function currently only support node 10 We have to use node 10 for all workspace pages Recommend using fnm for better performance

**Comment by zhigang1992** [comment]
> Because firebase cloud function currently only support node 10 We have to use node 10 for all workspace pages Recommend using fnm for better performance

We've [update the doc](https://tappollo.github.io/booster/#/start/quickstart?id=quick-start)

> I updated functions/package.json:

Unfortunately, that would break cloud function deployment. 

Our current solution is just to use node 10, we have a `.node-version` file at the root of the project, if you use nvm or fnm, it should be able to pick up and use node 10 for this project automatically.

**Comment by CoooWeee** [comment]
Oh, sorry I used node >13. My mistake.
