### ISSUE TITLE
Missing dependencies for user.ts to work

### ISSUE THREAD

**Issue by CoooWeee** [tappollo/booster#30]
user.ts is using lots of local dependencies which I believe are not referenced or should be global (expl. typescript).

Maybe something like
```
  "devDependencies": {
    ....
    "@types/fs-extra": "^8.0.1",
    "firebase-cli": "^1.2.0",
    "fs-extra": "^8.1.0",
    "meow": "^6.0.0",
    "node-ts": "^5.0.3",
    "ora": "^4.0.3",
    "path": "^0.12.7",
    "ts-node": "^8.5.4",
    "typescript": "^3.7.4"
  }
```

Btw the manual is saying to use:

```
yarn firebase deploy
yarn firebase login
```

There are not entries for in the script section. Or maybe better, just running it without yarn.

**Comment by zhigang1992** [comment]
Unfortunately it won’t work without yarn, it’s using yarn workspace. So there are more than one package.json. There one for each sub project. Doing yarn on root will install all of them.

More details here 

https://yarnpkg.com/lang/en/docs/workspaces/
